# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1af302f010d61c7fe0ca8d17ba7f8a609e514650a8bc2ceb842ecc43536247f4e57f02f1cdda27d3a0730db661268569f7d96ca2953c010a1bc01fe7600a3ef7

test:
  secret_key_base: eeb02a726898ee2886dbd01a07a7e094cd09e174a9d7f68402b668cedf19f5f88a8d8df7eea3890c39dacb90786936e1182ac6a513640f337543c68f1c745f64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
